home_ScoreBoard:
    path:     /
    defaults: { _controller: ScoreBoardBundle:ScoreBoard:home }

match_ScoreBoard:
    path:     /match/{id}
    defaults: { _controller: ScoreBoardBundle:ScoreBoard:match }

contact_ScoreBoard:
    path:     /contact
    defaults: { _controller: ScoreBoardBundle:ScoreBoard:contact }

creation_ScoreBoard:
    path:     /match
    defaults: { _controller: ScoreBoardBundle:ScoreBoard:create }

team_ScoreBoard:
    path:     /team
    defaults: { _controller: ScoreBoardBundle:ScoreBoard:team }

createtournament_ScoreBoard:
    path:     /tournament
    defaults: { _controller: ScoreBoardBundle:ScoreBoard:createtournament }

tournament_ScoreBoard:
    path:     /tournament/{id}
    defaults: { _controller: ScoreBoardBundle:ScoreBoard:tournament }