<?php

namespace ScoreBoardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatchsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchsRepository extends EntityRepository
{

	public function matchsTableau()
	{
        $qb = $this
        ->createQueryBuilder('m')
        ->where('Matchs.id = Matchs_Team.Matchs_id')
        ->andWhere('Team.id = Matchs_Team.Team_id');

        return $qb
        ->getQuery()
        ->getResult();
    }

    public function timeLineTableau($id)

    {
    	$qb = $this->createQueryBuilder('t')->where('Timeline.match_id = '+ $id);
    	return $qb->getQuery()->getResult();
    }

}
